services:
  - type: web
    name: fastapi-legal-gemini
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: TEAM_AUTH_TOKEN
        sync: false
    plan: free