# render.yaml
services:
  - type: web
    name: llm-query-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /docs # Or /redoc, or a custom /health endpoint if you create one
    envVars:
      - key: GEMINI_API_KEY
        # You can set this as a secret environment variable directly in Render UI for security
        # Or uncomment and set value here for quick testing (NOT RECOMMENDED for production)
        # value: your_actual_gemini_api_key_here
      - key: TEAM_AUTH_TOKEN
        # Similarly, set as a secret in Render UI
        # value: 379374d4fa56b09c028f61908d40ba07a8ee9c8d6242ef105013b8724cb82ba96
    # Optional: Scaling to save resources
    scaling:
      minInstances: 0 # Spin down after inactivity
      maxInstances: 1 # Max instances for free tier